### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by sbarzowski** [waisbrot/yaml2jsonnet#1]
I think this is going to be very useful to many people. It would be easier to install if it was available via `pip`. Would you consider uploading the package to PyPI?

**Comment by waisbrot** [comment]
Thanks for the words of encouragement! I do plan to upload to PyPI. I haven't pushed a Python package before, though, so I have some reading/learning to do first. Probably this weekend I'll spend time getting the Github Actions to work, and one of them can be to push a package for tagged releases.

In the mean time, I'd love to have more confidence that the tool works for other people so if you have any examples you're able to throw my way (a really gigantic YAML file? A directory full of YAML?) I'd be interested in more test-cases. The property-based test I wrote was really fun (shiny new tool!) but isn't comprehensive.

**Comment by sbarzowski** [comment]
> I haven't pushed a Python package before, though, so I have some reading/learning to do first.

I'm not an expert in this stuff either, but if you run into any problems I'll be happy to help (or at least try to).

> if you have any examples you're able to throw my way 

The YAMLs I have are unfortunately confidential, but there's a lot of interesting stuff on Github:
https://github.com/search?q=kubernetes+extension%3Ayaml&type=Code&ref=advsearch&l=&l=

If you are interested in weird cases, it's probably easiest to get them from rants about YAML :-) E.g. https://www.arp242.net/yaml-config.html. I would worry mostly about the sane subset that people actually use, though. Supporting all of the weird boundary cases without exception is probably impossible anyway.

**Comment by waisbrot** [comment]
Got it working! https://pypi.org/project/yaml2jsonnet/
